apiVersion: v2
name: postgresql
version: 1.0.0
dependencies:
  - name: postgresql
    version: "16.2.1"  # Check latest: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    repository: https://charts.bitnami.com/bitnami